### PR TITLE
check_fa_files script

### PR DESCRIPTION
**Pull request by araichoor**
This PR adds a `bin/check_fa_files` script, which checks for the observed Main tiles the presence of:
- the `$DESI_TARGET/fiberassign/tiles/trunk/???/fiberassign-TILEID.{fits.gz,png,log}` files;
- the `$DESI_ROOT/survey/fiberassign/main/???/TILEID-{tiles,sky,gfa,targ,scnd,too}.fits` files.
A call to that script could be done monthly.

The tiles list comes from tiles with `STATUS="unobs"` in `tiles-main.ecsv`.
If some expected files are missing, those are reported in a printed table (along with the nights where those tiles have been observed), and some `log.error()` messages are printed at the end.
See below for an example.

Comments/Questions:
- the script has no arguments for now; I thought that we want to run this only for the Main survey (the SV1,2,3 surveys have different structures for the intermediate products), and all paths will remain the same (i.e. no need to make them arguments);
- I welcome any suggestion for a script name more relevant than `check_fa_files`;
- a possible case (though I'm not sure it can happen): if the `$DESI_SURVEYOPS/ops/` and `$DESI_TARGET/fiberassign` are out of sync, the tiles from the previous nights could appear with the `fiberassign*` files missing; in that case, the reported nights will make it clear it is just a matter of a one-day out-of-sync;
- it takes ~2 minutes to run for the 2.5k tiles observed so far.

I copy below an example of the generated output (currently, 58 tiles have some missing files, likely because `validate_lastnight_fba` has not been run for three nights, 20211112, 20220101, 20220105):
```
INFO:check_fa_files:85:main: Veryfing 2829 tiles from the MAIN survey with STATUS!=unobs

============= MISSING FILES FOR 58 TILES ===============
TILEID fafits fapng falog tiles sky  gfa  targ  scnd  too   NIGHTS 
------ ------ ----- ----- ----- ---- ---- ---- ----- ----- --------
  1687  False False False  True True True True  True False 20220101
  2354  False False False  True True True True  True False 20220105
  2355  False False False  True True True True  True False 20220105
  2380  False False False  True True True True  True False 20220105
  2474  False False False  True True True True  True False 20220101
  2477  False False False  True True True True  True False 20211112
  2480  False False False  True True True True  True False 20220105
  2567  False False False  True True True True  True False 20211112
  3713  False False False  True True True True  True False 20211112
  3932  False False False  True True True True  True False 20220105
  4040  False False False  True True True True  True False 20220105
  4053  False False False  True True True True  True False 20211112
  4102  False False False  True True True True  True False 20211112
  4598  False False False  True True True True  True False 20220105
  4707  False False False  True True True True  True False 20220101
  4838  False False False  True True True True  True False 20211112
  5666  False False False  True True True True  True False 20220105
  5685  False False False  True True True True  True False 20211112
  5966  False False False  True True True True  True False 20220101
  6152  False False False  True True True True  True False 20220105
  6210  False False False  True True True True  True False 20211112
  6514  False False False  True True True True  True False 20211112
  6732  False False False  True True True True  True False 20211112
  7062  False False False  True True True True  True False 20220105
  7135  False False False  True True True True  True False 20220105
  7239  False False False  True True True True  True False 20220105
  7704  False False False  True True True True  True False 20220105
  7770  False False False  True True True True  True False 20211112
  8263  False False False  True True True True  True False 20211112
  8307  False False False  True True True True  True False 20211112
  8633  False False False  True True True True  True False 20220105
  8680  False False False  True True True True  True False 20211112
  8771  False False False  True True True True  True False 20220105
  9289  False False False  True True True True  True False 20220105
  9299  False False False  True True True True  True False 20220105
  9518  False False False  True True True True  True False 20220101
 10206  False False False  True True True True  True False 20211112
 10354  False False False  True True True True  True False 20211112
 10358  False False False  True True True True  True False 20211112
 10381  False False False  True True True True  True False 20220101
 10818  False False False  True True True True  True False 20220105
 10860  False False False  True True True True  True False 20220101
 10873  False False False  True True True True  True False 20220105
 11077  False False False  True True True True  True False 20211112
 11088  False False False  True True True True  True False 20211112
 11355  False False False  True True True True  True False 20220105
 11536  False False False  True True True True  True False 20211112
 11769  False False False  True True True True  True False 20220105
 11808  False False False  True True True True  True False 20220105
 11913  False False False  True True True True  True False 20211112
 11932  False False False  True True True True  True False 20220105
 21571  False False False  True True True True  True False 20220101
 22070  False False False  True True True True  True False 20211112
 23925  False False False  True True True True  True False 20211112
 23937  False False False  True True True True  True False 20211112
 24632  False False False  True True True True  True False 20220101
 24655  False False False  True True True True  True False 20220101
 40064  False False False  True True True True False False 20220101
=======================================================

ERROR:check_fa_files:151:main: TILEID-tiles.fits: missing 58 files
ERROR:check_fa_files:151:main: TILEID-sky.fits: missing 58 files
ERROR:check_fa_files:151:main: TILEID-gfa.fits: missing 58 files
ERROR:check_fa_files:151:main: TILEID-targ.fits: missing 58 files
ERROR:check_fa_files:151:main: TILEID-scnd.fits: missing 57 files

```

### CODE REVIEW

**Comment by araichoor** [comment]
I don't know if there is someone "in charge" for that desisurveyops repository; @ashleyjross would you know?
If no suggestions from others, I'm happy with that PR, and I can merge it.
As there is no rush, I can wait few days more.

**Comment by schlafly** [comment]
My two cents: go ahead and merge.  I am happy to declare you "in charge" of
the repository.  :-)

**Comment by ashleyjross** [comment]
Same

**Comment by araichoor** [comment]
ok perfect, thanks, merging now.

**Pull request merged**
